// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsProfiler.DAL.DAL;

namespace SportsProfiler.DAL.Migrations
{
    [DbContext(typeof(SportsProfilerDataContext))]
    partial class SportsProfilerDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview3-35497");

            modelBuilder.Entity("SportsProfiler.Models.Models.SportsProfilerUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("UserId");

                    b.ToTable("SportsProfilerUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
